# -*- coding: utf-8 -*-
"""Calculadora em Python, com estrutura condicional de repetição:.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rwLVXc29ZRo99OP_OObGmhtQKeESeQkl

#Calculadora em Python, com estrutura condicional de repetição:
"""

#Calculadora em Python

 #Receba a entrada do usuário:

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

#Adicionando funções aritméticas:

 soma = num1 + num2
 subtracao = num1 - num2
 multiplicacao = num1 * num2
 divisao = num1 / num2

#Criar um laço de repetição:

 operacao = input("Digite a operação desejada (+, -, *, /): ")

 if operacao == "+":
   print("Resultado: ", soma)
 elif operacao == "-":
   print("Resultado: ", subtracao)
 elif operacao == "*":
   print("Resultado: ", multiplicacao)
 elif operacao == "/":
   print("Resultado: ", divisao)
 else:
   print("Operação inválida.")

#Código da calculadora, contínuo:

num1 = float(input("Digite o primeiro número: "))
num2 = float(input("Digite o segundo número: "))

soma = num1 + num2
subtracao = num1 - num2
multiplicacao = num1 * num2
divisao = num1 / num2

operacao = input("Escolha a operação (+, -, *, /): ")

if operacao == '+':
  print("Resultado:", soma)
elif operacao == '-':
  print("Resultado:", subtracao)
elif operacao == '*':
  print("Resultado:", multiplicacao)
elif operacao == '/':
  print("Resultado:", divisao)
else:
  print("Operação inválida!")

