# -*- coding: utf-8 -*-
"""Calculadora em Python, com loop de repetição.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-JqTSMsfnkOxPsMpX4HliQ9k45aTI5mT

#Calculadora em Python, com loop de repetição:
"""

#Calculadora em Python

    #Definir a saída ao usuário em um loop de repetição:

  while True:
    print("\nOperações:")
    print("1. Adição")
    print("2. Subtração")
    print("3. Multiplicação")
    print("4. Divisão")
    print("5. Sair")

    #Definir a entrada de acordo com a escolha do usuário:

    escolha = input("Escolha uma operação (1-5): ")

    #Definir a opção de entrada em uma estrutura condicional:

    if escolha == '5':
      print("Calculadora encerrada.")
      break

    try:
      num1 = float(input("Digite o primeiro número: "))
      num2 = float(input("Digite o segundo número: "))

      if escolha == '1':
        resultado = num1 + num2
        print("Resultado:", resultado)
      elif escolha == '2':
        resultado = num1 - num2
        print("Resultado:", resultado)
      elif escolha == '3':
        resultado = num1 * num2
        print("Resultado:", resultado)
      elif escolha == '4':
        if num2 == 0:
          print("Erro: Divisão por zero não permitida.")
        else:
          resultado = num1 / num2
          print("Resultado:", resultado)
      else:
        print("Opção inválida.")

    #Definir um tratamento de erros em caso de dados inválidos:

    except ValueError:
      print("Erro: Entrada inválida. Certifique-se de digitar números.")

    #Inicia a calculadora:

calculadora()